import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotesProvider } from "./context/NotesContext";
import { Providers } from "@/app/providers";
import Navbar from "./components/navbar";
import AuthProvider from "@/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevNotes",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}  suppressHydrationWarning>
      <body >
        <AuthProvider>
          <Providers>
            <NotesProvider>
              <Navbar />
              {children}
            </NotesProvider>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}

